/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PositionsRouteImport } from './routes/positions'
import { Route as MintPositionRouteImport } from './routes/mint-position'
import { Route as IndexRouteImport } from './routes/index'

const PositionsRoute = PositionsRouteImport.update({
  id: '/positions',
  path: '/positions',
  getParentRoute: () => rootRouteImport,
} as any)
const MintPositionRoute = MintPositionRouteImport.update({
  id: '/mint-position',
  path: '/mint-position',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mint-position': typeof MintPositionRoute
  '/positions': typeof PositionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mint-position': typeof MintPositionRoute
  '/positions': typeof PositionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mint-position': typeof MintPositionRoute
  '/positions': typeof PositionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mint-position' | '/positions'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mint-position' | '/positions'
  id: '__root__' | '/' | '/mint-position' | '/positions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MintPositionRoute: typeof MintPositionRoute
  PositionsRoute: typeof PositionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/positions': {
      id: '/positions'
      path: '/positions'
      fullPath: '/positions'
      preLoaderRoute: typeof PositionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mint-position': {
      id: '/mint-position'
      path: '/mint-position'
      fullPath: '/mint-position'
      preLoaderRoute: typeof MintPositionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MintPositionRoute: MintPositionRoute,
  PositionsRoute: PositionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
