blank_issues_enabled: false
contact_links:
  - name: Security Policy
    url: https://github.com/atom-fi/atom.fi-api/security/policy
    about: Please report security vulnerabilities responsibly via the security policy.

